---
apiVersion: v1
kind: Service
metadata:
  name: business-service
  labels:
    app.kubernetes.io/name: business-deployment
spec:
  ports:
    - port: 8080
      name: http-common
      targetPort: 8080
  selector:
    app.kubernetes.io/name: business-deployment