apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-deployment
  labels:
    app.kubernetes.io/name: time-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: time-deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: time-deployment
    spec:
      containers:
        - name: time
          image: "yurisc/bootcamp:time"