---
apiVersion: v1
kind: Service
metadata:
  name: time-service
  namespace: bootcamp
  labels:
    app.kubernetes.io/name: time-deployment
spec:
  ports:
    - port: 80
      name: http-common
      targetPort: 8080
  selector:
    app.kubernetes.io/name: time-deployment
