---
apiVersion: v1
kind: Service
metadata:
  name: time-service-node-port
  namespace: bootcamp
  labels:
    app.kubernetes.io/name: time-deployment
spec:
  ports:
    - port: 8080
      name: http-common
      targetPort: 8080
      nodePort: 30800
  selector:
    app.kubernetes.io/name: time-deployment
  type: NodePort
