apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-deployment
  namespace: bootcamp
  labels:
    app.kubernetes.io/name: business-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: business-deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: business-deployment
    spec:
      containers:
        - name: business
          image: "yurisc/bootcamp:business"
          env:
            - name: TIME_SERVICE_HOST
              value: "time-service"
