---
apiVersion: v1
kind: Service
metadata:
  name: bussiness-service-node-port
  namespace: bootcamp
  labels:
    app.kubernetes.io/name: business-deployment
spec:
  ports:
    - port: 8080
      name: http-common
      targetPort: 8080
      nodePort: 30811
  selector:
    app.kubernetes.io/name: business-deployment
  type: NodePort
